### PR TITLE
Fix: Velocity in PhysicsEngine

### LINKED ISSUE #382: PhyscisEngine Velocity Bug -- Incorrect dt
I am working on porting a physics component from `famous` to `engine` and I cannot get `Drag` to behave correctly.  I am trying to apply friction and drag to a single particle as in the old `Scroller`.  However, when I use the same configuration in `engine`, the elements do not scroll as expected.

Is anyone familiar with the changes between the first `famous` and the current `engine`?

### PR DESCRIPTION
**Pull request by jd-carroll**
Fixes #382

### CODE REVIEW

**Comment by browles** [comment]
This changes the units of the engine from seconds to milliseconds.

More of a difference in opinion rather than a fix.

**Comment by jd-carroll** [comment]
@browles It would be a matter of opinion if **every other unit** was also in seconds.  There is no documentation that velocity and constraints use seconds.  What have you been using to calculate the velocity of a touchmove?

Can you please merge this change so that this will be consistent with the rest of the platform.  It does not make sense to have to scale velocity to milliseconds only to have to scale the delta to milliseconds as well.  Though these calculations are insignificant, they are unnecessary.

**Comment by browles** [comment]
I'm not sure what you're getting at. All notions of velocity across the platform are in seconds. This will ruin consistency.

**Comment by browles** [comment]
What would be fine is a way to specify the units of time you would like the engine to use.

**Comment by michaelobriena** [comment]
As noted in #382, I think that ms units is more intuitive.  Going to close this as it does not seem to be a change we want to include.

**Pull request closed without merging**
