### PR TITLE
Frame Rate Debug Utility

### PR DESCRIPTION
**Pull request by jd-carroll**
When debugging through the `PhysicsEngine`, it is _very_ useful to step through the code for multiple frames.  The current rAF will set the time for the next frame based on how long you were debugging.  It would be useful to have an option to set a constant time frame rate when debugging.

### CODE REVIEW

**Comment by alexanderGugel** [comment]
This should be implemented in `core/Clock.js`. In `Clock#step`, just add `time = this._frameRate ? this._time + this._frameRate : time`.

Putting this in the `RequestAnimationFrame` loop makes it a nightmare to debug the worker build. The clock is meant for things like that (e.g. fixed frame rate, fps cap, time scaling are all things that belong in there IMO).

**Comment by jd-carroll** [comment]
@alexanderGugel good point, let me rework

**Comment by michaelobriena** [comment]
@jd-carroll also, we should add a special rendering loop that allows the user to trigger frames manually.

**Comment by michaelobriena** [comment]
@jd-carroll I like this idea but would not want to add this code until we could strip it.

**Comment by alexanderGugel** [comment]
@michaelobriena Agreed. I was thinking of not hiding this as an option used for debugging (at least not explicitly), but exposing it as a regular method. The old engine also had a method [setFPSCap](https://github.com/Famous/famous/blob/develop/src/core/Engine.js#L261). Although doing this would probably make more sense in engine than clock.

**Comment by alexanderGugel** [comment]
What's the status of this?

I like the idea, but I'm not happy with the current implementation. I think this should either be

1. A normal option (without the debug flag, the overhead is pretty limited, it could probably be dead code eliminated)
2. Be a separate loop

Also it might be better to place this in the Clock, since debugging across threads in the web worker build is kind tricky at times, so normalizing the time there might be a better idea.

@michaelobriena Do we want to bring this into the platform?

**Comment by jd-carroll** [comment]
@alexanderGugel @michaelobriena If you guys decide on a path forward for this, I'd be happy to make the necessary changes

**Pull request closed without merging**
