### PR TITLE
Clean: Add appropriate docs for getting the WebGL context

### PR DESCRIPTION
**Pull request by FarhadG**

### CODE REVIEW

**Comment by michaelobriena** [comment]
We should not throw if they do not have webGL support and try to use it.

**Comment by FarhadG** [comment]
@michaelobriena 

Should we just console.log? This refers to the issues that some are having when their system doesn't support WebGL.

**Comment by michaelobriena** [comment]
Yes, just warn and make sure the code protects from breaking.  If you use Mesh you should be able to have the rest of you app work even if WebGL is not enabled.

**Comment by FarhadG** [comment]
@michaelobriena 

Updated with `console.error` messages, so that it doesn't throw and block.

**Comment by michaelobriena** [comment]
Thanks @FarhadG

**Comment by michaelobriena** [comment]
landed as d32b28a

**Pull request closed without merging**
