### PR TITLE
[Fixes #95482090] fix: .getUniformLocation bug

### PR DESCRIPTION
**Pull request by redwoodfavorite**

### CODE REVIEW

**Comment by michaelobriena** [comment]
@redwoodfavorite can you rewrite the commit structure to be start with the fix: and end with the pivotal information?

**Comment by redwoodfavorite** [comment]
:+1:

**Comment by michaelobriena** [comment]
@redwoodfavorite Thanks.

**Comment by michaelobriena** [comment]
@FarhadG @adnan-wahab Can you review?

**Comment by FarhadG** [comment]
@michaelobriena 

+1 Looks good!

**Comment by adnan-wahab** [comment]
+1

**Comment by michaelobriena** [comment]
landed as 1774b67

**Pull request closed without merging**
