### PR TITLE
Do not process multiple CONTEXT_RESIZE

### LINKED ISSUE #396: Duplicate NEED_SIZE_FOR commands processed when creating Context
When you create a `Context`, the newly created `Context` will automatically request its size through a `NEED_SIZE_FOR` command.  Once created, the `Scene` will request a duplicated `NEED_SIZE_FOR` which is unnecessary.

### PR DESCRIPTION
**Pull request by jd-carroll**
Fixes #396

### CODE REVIEW

**Comment by michaelobriena** [comment]
@jd-carroll you have a failing test.  Maybe need a rebase?

**Comment by jd-carroll** [comment]
@michaelobriena The test that is failing is:
`✗ All vectors should be within 2x2 bounding box`

This seems to be the manifestation of #364, so I'm not sure if there is something I'm doing that is causing this or what.  But, I'm not too sure how to fix this...

**Comment by michaelobriena** [comment]
Gotcha, will look into this.

**Comment by michaelobriena** [comment]
landed as 6f8336f

**Pull request closed without merging**
