### PR TITLE
Don't check an instance constructor for static properties since that might not be the same when classes extend.

### LINKED ISSUE #385: [BUG] Same example as in #383, but throws an error with engine-seed.
I've taken the working sample that I've shown in #383 and tried to run it in engine-seed (off of commit [d317ce45cb](https://github.com/Famous/engine-seed/tree/d317ce45cba536dc5428e8e5c4355632468842e7)). The only change I've made to the source is change the `famous.*.*` dependencies to `require('famous/*/*')` format. Now instead of the code running like you'll see if you paste the example from #383 into a famous.org editor, you'll see this error:

```
Uncaught Error: This node does not have access to a transform component
```

Here's a link to the branch of my engine-seed fork where this error happens: https://github.com/trusktr/engine-seed/tree/position-bug

If you change line 116 from

```js
                    let cardNode = scene.addChild(new BetterNode)
```

to

```js
                    let cardNode = scene.addChild(new Node)
```

You'll notice that not using the extended Node class results in the error going away! (I was lacking a name for the extended Node so, BetterNode. :laughing:)

### PR DESCRIPTION
**Pull request by trusktr**
Fixes #385

### CODE REVIEW

**Comment by alexanderGugel** [comment]
:+1: Not pretty, but it works and is stable. Copying over the static properties from the Node to all subclasses or decorating the constructor in the Node constructor would also be an alternative.

**Comment by jd-carroll** [comment]
Please do not merge this, it will break proportional sizing.

For reference please look at: #354 
Also #353 & #350

**Comment by trusktr** [comment]
@jd-carroll Good catches! I wonder what's the best approach to this. @alexanderGugel I think perhaps decorate the constructor if the property isn't already defined on the constructor.

**Comment by trusktr** [comment]
@jd-carroll @alexanderGugel Made changes. What do you think?

**Comment by jd-carroll** [comment]
This is exactly what I had in my original PR #355.  However, in discussions with @DnMllr he identified that the constants are unnecessary and should actually be removed in favor of the constants in `Size`.

I also just realized, **this PR is against the wrong branch**.  Should be merged with develop not master.  If this was merged against develop then you would see the conflict because this case has already been addressed.

@trusktr Please update your dependency in your project to:

```
  ...
  "dependencies": {
    "babelify": "^6.0.1",
    "famous": "git://github.com/famous/engine#develop"
  }
```

If you still have problems after updating your dependency please repost.

**Comment by trusktr** [comment]
@jd-carroll Oops! Closing this since it's on master.

**Comment by trusktr** [comment]
@alexanderGugel @jd-carroll @DnMllr Continuing at #387.

**Pull request closed without merging**
