### PR TITLE
fix: removing dependency on geometry in WebGLRenderer

### PR DESCRIPTION
**Pull request by redwoodfavorite**
Fixes -> https://github.com/Famous/engine/issues/165

### CODE REVIEW

**Comment by michaelobriena** [comment]
This looks pretty good.

A few questions I have:

- Why did you remove the dependency of Plane?  This seems like an unneeded duplication of that logic.
- How much effort would it take to have a special case for border-radius of a DOM element so that we can use custom shaders to make the cutouts non-rectangular?  I think this is something we have all known the limitations of but I am starting to think that we should prioritize this a lot higher.

**Comment by redwoodfavorite** [comment]
1.  Removed actual geometry from WebGL geometry because we are running into the same issue with browserify and require statements in the worker thread incrementing seperate counters for geometry Ids.  -> https://github.com/Famous/engine/issues/165

2.  Border radius is definitely something we could do, I'd imagine it'd be some custom shader logic to discard some pixels based on border-radius but we should all talk about it if it is indeed a priority.

**Comment by michaelobriena** [comment]
@FarhadG @adnan-wahab Can you review?

**Comment by adnan-wahab** [comment]
looks good to me.

**Comment by FarhadG** [comment]
Looks good!

@michaelobriena

**Comment by michaelobriena** [comment]
landed as 3eae1b9

**Pull request closed without merging**
