### PR TITLE
fixed typo

### PR DESCRIPTION
**Pull request by mikestaub**

### CODE REVIEW

**Comment by michaelobriena** [comment]
@mikestaub Thanks!  Can you sign the CLA?

**Comment by michaelobriena** [comment]
http://famous.org/cla/

**Comment by mikestaub** [comment]
Done.

**Comment by michaelobriena** [comment]
Thanks!

**Comment by michaelobriena** [comment]
Thanks for the PR mike but I did not realize that agcolom's pr already had this too.  https://github.com/Famous/engine/pull/176/files

Thanks for the PR though!

**Pull request closed without merging**
