### PR TITLE
docs: fix return value

### PR DESCRIPTION
**Pull request by Imti**
Function: Node.prototype.getRotation()

Before: * @return {undefined} undefined
After:  * @return {Node} this

### CODE REVIEW

**Comment by alexanderGugel** [comment]
@Imti Can you rebase?

**Comment by michaelobriena** [comment]
@Imti ping

**Comment by Imti** [comment]
@michaelobriena @alexanderGugel rebased

**Comment by michaelobriena** [comment]
landed as 034e4c5

**Pull request closed without merging**
