### PR TITLE
Fix: showing child components on hide in Node [#97865428]

### PR DESCRIPTION
**Pull request by redwoodfavorite**
fixes -> https://github.com/Famous/engine/issues/345

### CODE REVIEW

**Comment by alexanderGugel** [comment]
This should be done in the Dispatch, not the Node IMO. Just to be consistent (like in `Dispatch#mount` and `Dispatch.dismount`).

( https://github.com/Famous/engine/blob/master/core/Dispatch.js#L208 )

**Comment by redwoodfavorite** [comment]
Good point Alex. Changed.

**Comment by michaelobriena** [comment]
@redwoodfavorite can you provide an example with this fix?

**Comment by michaelobriena** [comment]
landed as 3ccd502

**Pull request closed without merging**
