### PR TITLE
fix: removing breaking bug where canvas size is attempted to be set w…

### PR DESCRIPTION
**Pull request by redwoodfavorite**
…hen no size is passed into updateSize

### CODE REVIEW

**Comment by redwoodfavorite** [comment]
Also fixes duplicate switch case issue that is failing travis build!

**Comment by adnan-wahab** [comment]
+1!!!!

**Comment by alexanderGugel** [comment]
:+1000:

**Comment by michaelobriena** [comment]
landed as 427adea

**Pull request closed without merging**
