### PR TITLE
update browserify

### PR DESCRIPTION
**Pull request by TheAlphaNerd**

### CODE REVIEW

**Comment by alexanderGugel** [comment]
@TheAlphaNerd Something went wrong here.

**Comment by alexanderGugel** [comment]
Is there anything that prevents us from updating browserify?

**Comment by michaelobriena** [comment]
@TheAlphaNerd we good to rebase and make the change on this?

**Comment by TheAlphaNerd** [comment]
ima close this and reopen with a fresh commit

**Comment by alexanderGugel** [comment]
@TheAlphaNerd See #201

**Pull request closed without merging**
