### PR TITLE
Feat: Add support for Hi-DPI screens

### PR DESCRIPTION
**Pull request by FarhadG**

### CODE REVIEW

**Comment by FarhadG** [comment]
@michaelobriena 

Examples were updated to show functionality on mixed-mode-examples. I think we should clean them up and make those available to the public as well?

**Comment by michaelobriena** [comment]
I would like them to be public but right now they are not in a great state.  That said, I think we have more important things to do than clean those up right now since we have an suitable amount of tutorials for the time being.

**Comment by michaelobriena** [comment]
Can you revert your changes to the CSS files?  This pluses at the end of the line is a more used convention.

**Comment by FarhadG** [comment]
@michaelobriena 

:+1: Got it.

**Comment by michaelobriena** [comment]
@FarhadG TY

**Comment by FarhadG** [comment]
https://github.com/Famous/engine/pull/228

**Pull request closed without merging**
