### PR TITLE
fix: Reset cutout on dismount

### PR DESCRIPTION
**Pull request by alexanderGugel**
Quick fix for #245 until DOMElement is rewritten.

@redwoodfavorite

### CODE REVIEW

**Comment by redwoodfavorite** [comment]
@alexanderGugel This will work but I want to rewrite setCutoutState handling in renderer.

**Comment by alexanderGugel** [comment]
:+1:

**Comment by redwoodfavorite** [comment]
On second thought, these refactors aren't entirely necessary yet.  Perhaps when the new Renderers/Context changes come in but this PR should solve the issue for now. :+1:

**Comment by michaelobriena** [comment]
landed as 5b88db5

**Pull request closed without merging**
