### PR TITLE
chore: update build script

### PR DESCRIPTION
**Pull request by TheAlphaNerd**
* created a dist folder with a .keep file in it
  * you will no longer need the ```mkdir dist;``` in the build scripts (breaking for window)
* create build task for unminified source with source maps.
* create meta-build task to execute both builds

### CODE REVIEW

**Comment by michaelobriena** [comment]
Great idea.

**Comment by alexanderGugel** [comment]
:+1:

I think this should be submitted to `develop`?

**Comment by TheAlphaNerd** [comment]
in reality we should never be hitting the green merge button. The branch a PR is sent to really means nothing (aside from not cluttering the github interface)

**Comment by michaelobriena** [comment]
landed as c669bdf

**Pull request closed without merging**
