### PR TITLE
wip: Refactor DOMElement

### PR DESCRIPTION
**Pull request by alexanderGugel**
# WIP - Don't merge yet.

The DOMElement is pretty chaotic currently (and has been subject to many bugs). State all over the place, inconsistent names (properties <-> style), missing getters (or only partial via hasClass) etc.

This PR is intended to gather some early feedback. I'm also adding reasonable tests for this.

There will be some backwards incompatible non-user facing/ backwards compatible user-facing API changes, including but not limited to the complete removal of methods that turned out to be confusing to users, despite being labeled as "private" (e.g. draw, init).

### CODE REVIEW

**Comment by alexanderGugel** [comment]
Update: Feature parity with previous version, rewrite tests

TODO: Complete cleanup logic, finish tests

**Comment by alexanderGugel** [comment]
obsolete #197

**Comment by michaelobriena** [comment]
@alexanderGugel I am going to close this.

For stuff that you want to make the community aware of, file an issue and link to your personal fork so people can track it.

Let's leave PR's as a safe place for stuff that is fully implements, tested, and doc'd.

**Comment by alexanderGugel** [comment]
@michaelobriena This is due to the fact that it hasn't been completely rebased yet. It was ready to merge  for a couple of days, but `feature-systems` has been merged in before.

**Pull request closed without merging**
