### PR TITLE
Material update uniform

### PR DESCRIPTION
**Pull request by adnan-wahab**

### CODE REVIEW

**Comment by michaelobriena** [comment]
@adnan-wahab can you look at the travis build?

**Comment by adnan-wahab** [comment]
Fixed

**Comment by michaelobriena** [comment]
@adnan-wahab build still failing

**Comment by adnan-wahab** [comment]
build fail was cause build was broken but joseph fixed it. rebased

**Comment by michaelobriena** [comment]
Can you provide an example for these fixes?

**Comment by adnan-wahab** [comment]
https://api-te.famo.us/codemanager/v1/containers/0e578483-207f-44ae-8ac8-3762962dfa31/share

**Comment by michaelobriena** [comment]
landed as 00c3489

**Pull request closed without merging**
