### PR TITLE
fix: initialize DOMElement with correct size mode

### LINKED ISSUE #160: Render size mode does not create and center true sized DOM element
screen shot 2015-05-21 at 7 25 03 pm
```js
scene.addChild()
  .setAlign(0.5, 0.5)
  .setMountPoint(0.5, 0.5)
  .setSizeMode(1, 1)
  .setAbsoluteSize(100, 70);  // <-- Absolute sizing works as expected
```
---
screen shot 2015-05-21 at 7 25 22 pm
```js
scene.addChild()
  .setAlign(0.5, 0.5)
  .setMountPoint(0.5, 0.5)
  .setSizeMode(2, 2);  // <- Render sizing does not center, and
                       //    it splits content into two lines. Why?
```
[source code](https://gist.github.com/pilwon/eea5126d50090eb48204)

### PR DESCRIPTION
**Pull request by browles**
Fixes #160

### CODE REVIEW

**Comment by alexanderGugel** [comment]
ok, this is very picky: Can we be explicit instead of using apply?

**Comment by michaelobriena** [comment]
I think apply is pretty correct in this case.

**Comment by DnMllr** [comment]
This is the right thing to do.

**Comment by pilwon** [comment]
This PR seems to fix the alignment problem, but there's still an issue determining true render size of content.

For example, setting `{content: 'Hello World'}` produces the following result (`Hello` and `World` are split into two lines):

![screen shot 2015-06-02 at 1 16 39 am]
(https://cloud.githubusercontent.com/assets/61540/7928924/b57419d0-08c5-11e5-8905-c98503cf1953.png)

[source code](https://gist.github.com/pilwon/eea5126d50090eb48204)

**Comment by michaelobriena** [comment]
@pilwon I think this solution is the correct way to handle this and the issues that you pointed out are a result of our default css we put on the body.  I think we should move forward with this fix and then tackle the "Hello World" being split up after the fact.

**Comment by pilwon** [comment]
@michaelobriena Thanks- It'd be great if the PR fixing the other part is linked from issue #160 so we could track that too.

**Comment by michaelobriena** [comment]
landed as bb40181

**Pull request closed without merging**
