### PR TITLE
docs: Fix @link doc

### PR DESCRIPTION
**Pull request by alexanderGugel**
See http://usejsdoc.org/tags-inline-link.html

### CODE REVIEW

**Comment by michaelobriena** [comment]
If we are going to keep these in, we need to add this linking ability to our doc generator, these are currently just plain text.

**Comment by michaelobriena** [comment]
That said, +1 for the time being

**Comment by alexanderGugel** [comment]
Yeah, standard JSDoc renders everything beautifully, but our doc generator seems to freak out about those links.

**Comment by michaelobriena** [comment]
landed as 04d83b3

**Pull request closed without merging**
