### PR TITLE
chore: Fix package.json license

### PR DESCRIPTION
**Pull request by alexanderGugel**

### CODE REVIEW

**Comment by alexanderGugel** [comment]
@michaelobriena This is starting to break stuff: https://travis-ci.org/Famous/engine/jobs/64839701#L119

**Comment by TheAlphaNerd** [comment]
Io 2.2 is broken on Travis.

There should be a patch out soon

**Comment by alexanderGugel** [comment]
Seems more like a npm bug to me, but maybe it's not related to the invalid license.

**Comment by TheAlphaNerd** [comment]
https://github.com/nodejs/io.js/issues/1850

It is an npm bug, but caused by the IO release

**Comment by michaelobriena** [comment]
landed as bb42572

**Pull request closed without merging**
