### PR TITLE
fix: add contextmenu to eventmap #290

### PR DESCRIPTION
**Pull request by adnan-wahab**

### CODE REVIEW

**Comment by adnan-wahab** [comment]
@DnMllr  please review

https://developer.mozilla.org/en-US/docs/Web/Events/contextmenu

bubbles TRUE
interface mouseEvent

**Comment by alexanderGugel** [comment]
Still not sure if we should implement this. It seems like no browser fully supports it. Fx also has only limited support: http://caniuse.com/#search=contextmenu

**Comment by alexanderGugel** [comment]
lgtm

**Comment by DnMllr** [comment]
@adnan-wahab I think this is fine.

@michaelobriena This has been open for a while we should figure out how to get this small change in.

**Comment by michaelobriena** [comment]
landed as 22ac87c

**Comment by michaelobriena** [comment]
landed as 076d913

**Pull request closed without merging**
