### PR TITLE
fix: Make Node#getChildren() return array without holes [#96509964]

### PR DESCRIPTION
**Pull request by alexanderGugel**

### CODE REVIEW

**Comment by michaelobriena** [comment]
Thoughts on having the method be polymorphic vs adding a brand new method?

**Comment by alexanderGugel** [comment]
No. Want me to make it polymorphic?

**Comment by jd-carroll** [comment]
Is there an update on this?  Not having this makes scroll view nodes a little more work.

**Comment by michaelobriena** [comment]
Landed as f732d50

**Pull request closed without merging**
