### PR TITLE
Fix: Fail when .obj file has trailing whitespace before carriage return

### PR DESCRIPTION
**Pull request by hannahhoward**
Hi, I hope this isn't too soon.

After your demo tonight, I started playing around with the OBJLoader, and after much trial and error discovered that if the .obj has any spaces at the end of lines in any of the face definitions, the loader reads it as a quad instead of a triangle, and adds an empty vertex for the fourth point. This simply removes any trailing white space before interpreting the face definition, and now loads the .obj I was working successfully.

### CODE REVIEW

**Comment by TheAlphaNerd** [comment]
@adnan-wahab / @redwoodfavorite 

thoughts?

**Comment by TheAlphaNerd** [comment]
@hannahhoward thanks for catching this!

We are going to need you to sign the CLA to merge this.

http://famous.org/cla

How are things down in southern California?

**Comment by hannahhoward** [comment]
things are good in SoCal! I'll go check the CLA -- thought I had signed already but maybe that was for the old one

**Comment by hannahhoward** [comment]
OK CLA Submitted

**Comment by redwoodfavorite** [comment]
@hannahhoward nice catch!  This looks good.

There seems to be some issues with the PR commits as soon as that's resolved this should be good to merge in.

@TheAlphaNerd

**Comment by TheAlphaNerd** [comment]
This should be manually handled, some last minute rebasing on our end

**Comment by adnan-wahab** [comment]
+1

**Comment by michaelobriena** [comment]
landed as 3051708

**Pull request closed without merging**
