### PR TITLE
fix: No longer stopPropagation on events

### PR DESCRIPTION
**Pull request by alexanderGugel**
Apparently screen readers have some problems with `stopPropagation`.

### CODE REVIEW

**Comment by DnMllr** [comment]
Because we already bubble events in our scene graph, if events bubble in the DOM too then we will have multiple copies of the same event flowing in our scene graph. This needs to be taken into consideration somehow if we want to change our stopPropagation rules.

**Comment by alexanderGugel** [comment]
@DnMllr This has already been taken into account. That's why keep track of the last event via `DOMRenderer#_lastEv`.

**Comment by alexanderGugel** [comment]
Added test case. Merge please.

**Comment by michaelobriena** [comment]
landed as 07b501d

**Pull request closed without merging**
