### PR TITLE
feat: add/remove instantiated scenes from the engine

### PR DESCRIPTION
**Pull request by browles**
Addresses #182

### CODE REVIEW

**Comment by browles** [comment]
Addresses #182

**Comment by browles** [comment]
@DnMllr @alexanderGugel

**Comment by alexanderGugel** [comment]
lgtm :+1:

**Comment by michaelobriena** [comment]
What is the use case for having Scene created in space?

**Comment by alexanderGugel** [comment]
@michaelobriena Are you referring to https://github.com/Famous/engine/pull/202/files#diff-1de37d20f8b6890668f053904aaf54d8R389 ? 

We allow detached nodes, so I think having detached scenes makes sense.

Further there might be scenarios in which the global updater itself should not be updated using FRAME commands, but should run its own rAF loop. E.g. AFAIR W3C had the discussion of allowing rAF in Workers.

In general there is no use in decoupling Scene and FamousEngine is we don't account for this scenario IMO.

**Comment by michaelobriena** [comment]
landed as e176693

**Pull request closed without merging**
