### PR TITLE
doc: fix typos

### PR DESCRIPTION
**Pull request by agcolom**

### CODE REVIEW

**Comment by agcolom** [comment]
This is the first PR, replacing https://github.com/Famous/engine/pull/88 which I believe can be closed?

**Comment by agcolom** [comment]
This covers components to physics. On that part, I have a few questions:
* https://github.com/Famous/engine/blob/master/core/Node.js#L54 
  * I understand you want to use 'Nodes' but with the 'each' I'd still go with 'has' instead of 'have' so ```Each Nodes have``` -> ```Each Nodes has```. Thoughts?
* https://github.com/Famous/engine/blob/master/physics/constraints/collision/SweepAndPrune.js#L183
  * is the double ```//``` intended or should ```// //``` be ```//```? (Note https://github.com/Famous/engine/blob/master/physics/constraints/collision/SweepAndPrune.js#L194)
* https://github.com/Famous/mixed-mode/blob/master/engine/Engine.js#L175
  * This sentence doesn't seem to make sense to be. Either a word is missing or shown should be in a different form

**Comment by michaelobriena** [comment]
1) Just out of the loop but was it communicated that we wanted to use "Nodes".  I would say, "Each Node has"

2) Totally a mistake

3) Dead link (Engine -> RequestAnimationFrameLooper since private beta)

**Comment by michaelobriena** [comment]
@agcolom Thanks!

**Comment by agcolom** [comment]
@michaelobriena Brilliant, thanks. So I can either add new commits to this PR or create a new one. I've read that you like commits to be squashed before submitting a PR, but since I've already submitted this one, I'm not sure how to squash additional commits. However, I believe this can easily be done when landing a PR by doing an interactive merge, so if you don't mind doing that for me when it's all ready to land, I can add the additional changes (ie points 1,2,3 above). Please let me know which solution works best for you.

**Comment by alexanderGugel** [comment]
@agcolom 

Instead of creating an additional commit, just solve the issues and do `git commit --amend` and `git push origin fixTypos --force`.

**Comment by agcolom** [comment]
@alexanderGugel Thank you! That seem to have worked!

**Comment by michaelobriena** [comment]
landed as 5f01a4a

**Pull request closed without merging**
